import type { Metadata } from "next";
import localFont from "next/font/local";
import { Merriweather } from 'next/font/google'
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Suspense } from "react";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const merriweather = Merriweather({
  weight: ['300', '400', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap', 
})

export const metadata: Metadata = {
  title: "Recipes App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body
          className={`${merriweather.className} antialiased`}
        >
          <NavBar />
          <main className="min-h-screen py-6 px-6 md:px-[50px] lg:px-[100px]">
            <Suspense fallback={null}>
              {children}
            </Suspense>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
